Properly initialize and return Error objects
Previously errors would be created like:

    var err = new Error({message: 'foo'});

If you try to print this via `console.log`, you get the message:

    Error: [object Object]

The constructor for error takes a string as the first argument, so instead of
passing a dictionary we just pass the string value.

Furthermore, instead of passing back bare dictionaries when inputs fail
validation, we pass back instances of Error objects, which have stack traces
attached, and would pass checks like (err instanceof Error).